//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patcher.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting {0}.
        /// </summary>
        internal static string adding_file {
            get {
                return ResourceManager.GetString("adding_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t verify current version of files. Please reinstall game..
        /// </summary>
        internal static string cant_get_current_version {
            get {
                return ResourceManager.GetString("cant_get_current_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t retrieve last version of files.  It&apos;s possible that the server have a technical issues.  If this error persists over a long period of time please contact the support of the game..
        /// </summary>
        internal static string cant_get_new_version {
            get {
                return ResourceManager.GetString("cant_get_new_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t download a update. Try to repeat attempt later..
        /// </summary>
        internal static string cant_get_patch {
            get {
                return ResourceManager.GetString("cant_get_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load configuration file: {0}.
        /// </summary>
        internal static string cant_load_configuration {
            get {
                return ResourceManager.GetString("cant_load_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking {0}.
        /// </summary>
        internal static string checking_file {
            get {
                return ResourceManager.GetString("checking_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for new updates....
        /// </summary>
        internal static string checking_new_version {
            get {
                return ResourceManager.GetString("checking_new_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking current version....
        /// </summary>
        internal static string checking_version {
            get {
                return ResourceManager.GetString("checking_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}.
        /// </summary>
        internal static string copying_file {
            get {
                return ResourceManager.GetString("copying_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}.
        /// </summary>
        internal static string deleting_file {
            get {
                return ResourceManager.GetString("deleting_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}. {1} of {2} ({3}%).
        /// </summary>
        internal static string downloading {
            get {
                return ResourceManager.GetString("downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in progress. Are you sure to want to quit ?.
        /// </summary>
        internal static string exit_confirmation {
            get {
                return ResourceManager.GetString("exit_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization....
        /// </summary>
        internal static string initialization {
            get {
                return ResourceManager.GetString("initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching a file {0} was interrupted. Can&apos;t apply patch because file was changed. Check your computer for viruses or reinstall game client..
        /// </summary>
        internal static string invalid_patch {
            get {
                return ResourceManager.GetString("invalid_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not exists: {0}.
        /// </summary>
        internal static string invalid_target_directory {
            get {
                return ResourceManager.GetString("invalid_target_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        internal static string launcher {
            get {
                return ResourceManager.GetString("launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading news....
        /// </summary>
        internal static string loading_news {
            get {
                return ResourceManager.GetString("loading_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching a file {0} was interrupted. Can&apos;t apply patch because patched file is broken. Check your computer for viruses or reinstall game client..
        /// </summary>
        internal static string patch_broke_client {
            get {
                return ResourceManager.GetString("patch_broke_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}.
        /// </summary>
        internal static string patching_file {
            get {
                return ResourceManager.GetString("patching_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You run patcher in debug mode. Patcher can&apos;t patch itself in this mode and exceptions may occur. Continue ?.
        /// </summary>
        internal static string run_without_target_directory {
            get {
                return ResourceManager.GetString("run_without_target_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing download....
        /// </summary>
        internal static string start_downloading {
            get {
                return ResourceManager.GetString("start_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred in progress of applying patch. We are very much apologize for it. If you even approximately&apos;t know why it has happened, then please make a screenshot and show it to the support service
        ///Message: {0}
        ///Stack: {1}.
        /// </summary>
        internal static string unknown_exception {
            get {
                return ResourceManager.GetString("unknown_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to patch....
        /// </summary>
        internal static string unpacking_patch_info {
            get {
                return ResourceManager.GetString("unpacking_patch_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string update_done {
            get {
                return ResourceManager.GetString("update_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string update_error {
            get {
                return ResourceManager.GetString("update_error", resourceCulture);
            }
        }
    }
}
